const teams = {
  '1': { name: 'New Jersey Devils', code: 'NJD', color: 'red' },
  '2': { name: 'New York Islanders', code: 'NYI', color: 'cyan' },
  '3': { name: 'New York Rangers', code: 'NYR', color: 'blue' },
  '4': { name: 'Philadelphia Flyers', code: 'PHI', color: 'yellow' },
  '5': { name: 'Pittsburgh Penguins', code: 'PIT', color: 'yellow' },
  '6': { name: 'Boston Bruins', code: 'BOS', color: 'yellow' },
  '7': { name: 'Buffalo Sabres', code: 'BUF', color: 'gray' },
  '8': { name: 'Montréal Canadiens', code: 'MTL', color: 'red' },
  '9': { name: 'Ottawa Senators', code: 'OTT', color: 'red' },
  '10': { name: 'Toronto Maple Leafs', code: 'TOR', color: 'blue' },
  '12': { name: 'Carolina Hurricanes', code: 'CAR', color: 'red' },
  '13': { name: 'Florida Panthers', code: 'FLA', color: 'gray' },
  '14': { name: 'Tampa Bay Lightning', code: 'TBL', color: 'blue' },
  '15': { name: 'Washington Capitals', code: 'WSH', color: 'red' },
  '16': { name: 'Chicago Blackhawks', code: 'CHI', color: 'red' },
  '17': { name: 'Detroit Red Wings', code: 'DET', color: 'red' },
  '18': { name: 'Nashville Predators', code: 'NSH', color: 'gray' },
  '19': { name: 'St. Louis Blues', code: 'STL', color: 'blue' },
  '20': { name: 'Calgary Flames', code: 'CGY', color: 'red' },
  '21': { name: 'Colorado Avalanche', code: 'COL', color: 'red' },
  '22': { name: 'Edmonton Oilers', code: 'EDM', color: 'yellow' },
  '23': { name: 'Vancouver Canucks', code: 'VAN', color: 'red' },
  '24': { name: 'Anaheim Ducks', code: 'ANA', color: 'gray' },
  '25': { name: 'Dallas Stars', code: 'DAL', color: 'green' },
  '26': { name: 'Los Angeles Kings', code: 'LAK', color: 'magenta' },
  '28': { name: 'San Jose Sharks', code: 'SJS', color: 'cyan' },
  '29': { name: 'Columbus Blue Jackets', code: 'CBJ', color: 'blue' },
  '30': { name: 'Minnesota Wild', code: 'MIN', color: 'green' },
  '52': { name: 'Winnipeg Jets', code: 'WPG', color: 'blue' },
  '53': { name: 'Arizona Coyotes', code: 'ARI', color: 'red' },
  '54': { name: 'Vegas Golden Knights', code: 'VGK', color: 'yellow' },
};

export default teams;
